cart_and_order/urls.py
from django.urls import path

from .views import (
    create_order,
    add_food_to_cart,
    clear_cart,
    get_cart_items,
    show_cart,
    remove_item_from_cart,
    update_item_quantity,
    show_orders,
    show_order_flutter,
    show_cart_flutter,
    add_food_to_cart_api,
    remove_food_from_cart_api,
    update_food_quantity_api,
    clear_cart_api,
    create_order_api
)

app_name = "order"

urlpatterns = [
    path("api/create_order/", create_order, name="create_order"),
    path('api/add_food_to_cart/<uuid:food_id>/', add_food_to_cart, name='add_food_to_cart'),
    path("api/clear_cart/", clear_cart, name="clear_cart"),
    path("api/cart/", get_cart_items, name="get_cart_items"),
    path("show_cart/", show_cart, name="show_cart"),
    path("api/remove_item_from_cart/<uuid:food_id>/", remove_item_from_cart, name="remove_item_from_cart"),
    path("api/update_item_quantity/<uuid:food_id>/", update_item_quantity, name='update_item_quantity'),
    path('orders/', show_orders, name='show_order_history'),

    # flutter
    path("api/show_orders/", show_order_flutter, name="order_history"),
    path('api/cart/add/<uuid:food_id>/', add_food_to_cart_api, name='add_food_to_cart_api'),
    path('api/cart/remove/<uuid:food_id>/', remove_food_from_cart_api, name='remove_item_from_cart_api'),
    path('api/cart/update/<uuid:food_id>/', update_food_quantity_api, name='update_item_quantity_api'),
    path('api/cart/clear/', clear_cart_api, name='clear_cart_api'),
    path('api/mobile_cart/', show_cart_flutter, name='get_cart_items_api'),
    path("api/mobile_create_order/", create_order_api, name="create_order_api"),
]

main/urls.py
from django.urls import path

from main.views import (
    get_user_data,
    login_user,
    logout_user,
    mobile_login,
    mobile_logout,
    mobile_register,
    register,
    show_main,
)

app_name = "main"

urlpatterns = [
    path("", show_main, name="show_main"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path("user/", get_user_data, name="get_user_data"),
    path("mobile_login/", mobile_login, name="mobile_login"),
    path("mobile_register/", mobile_register, name="mobile_register"),
    path("mobile_logout/", mobile_logout, name="mobile_logout"),
]

promo/urls.py
from django.urls import path
from promo.views import promo_home, add_promo, remove_promo, edit_promo, use_promo, promo_details, apply_promo, simulate_promo, mobile_promo_home, mobile_use_promo, mobile_promo_details, mobile_edit_promo, mobile_delete_promo, mobile_add_promo, owned_resto, check_promo_code, find_by_code, tag_promo, remove_promo_usage

app_name = 'promo'

urlpatterns = [
    path('', promo_home, name='promo_home'),
    path('add_promo/', add_promo, name='add_promo'),
    path('edit_promo/<uuid:promo_id>/', edit_promo, name='edit_promo'),
    path('remove_promo/<uuid:promo_id>/', remove_promo, name='remove_promo'),
    path('use_promo/<uuid:restaurant_id>/', use_promo, name='use_promo'),
    path('details/<uuid:promo_id>/', promo_details, name='promo_details'),
    path('apply_promo/', apply_promo, name='apply_promo'),
    path('simulate_promo/', simulate_promo, name='simulate_promo'),
    path('mobile_promo_home/', mobile_promo_home, name='mobile_promo_home'),
    path('mobile_use_promo/<uuid:restaurant_id>/', mobile_use_promo, name='mobile_use_promo'),
    path('mobile_promo_details/<uuid:promo_id>/', mobile_promo_details, name='mobile_promo_details'),
    path('mobile_edit_promo/<uuid:promo_id>/', mobile_edit_promo, name='mobile_edit_promo'),
    path('mobile_delete_promo/<uuid:promo_id>/', mobile_delete_promo, name='mobile_delete_promo'),
    path('mobile_add_promo/', mobile_add_promo, name='mobile_add_promo'),
    path('owned_resto/', owned_resto, name='owned_resto'),
    path('check_promo_code/<str:promo_code>/', check_promo_code, name='check_promo_code'),
    path('find_by_code/<str:promo_code>/', find_by_code , name='find_by_code'),
    path('tag_promo/', tag_promo , name='tag_promo'),
    path('remove_promo_usage/', remove_promo_usage, name='remove_promo_usage')
]

restaurant/urls.py
from django.urls import path

from .views import (
    create_food,
    create_restaurant,
    delete_food,
    delete_restaurant,
    restaurant_detail,
    restaurant_list,
    show_delete_food,
    show_delete_restaurant,
    show_restaurant_detail,
    show_restaurants,
    show_update_food,
    show_update_restaurant,
    update_food,
    update_restaurant,
)

app_name = "restaurant"

urlpatterns = [
    path("", show_restaurants, name="show_restaurants"),
    path("<uuid:id>/", show_restaurant_detail, name="show_restaurant_detail"),
    path("delete/<uuid:id>/", show_delete_restaurant, name="delete_restaurant"),
    path("update/<uuid:id>/", show_update_restaurant, name="update_restaurant"),
    path(
        "<uuid:restaurant_id>/delete_food/<uuid:food_id>/",
        show_delete_food,
        name="delete_food",
    ),
    path(
        "<uuid:restaurant_id>/update_food/<uuid:food_id>/",
        show_update_food,
        name="update_food",
    ),
    path("api/restaurants/", restaurant_list, name="restaurant_list"),
    path("api/restaurants/create/", create_restaurant, name="create_restaurant"),
    path(
        "api/restaurants/delete/<uuid:id>/", delete_restaurant, name="delete_restaurant"
    ),
    path(
        "api/restaurants/update/<uuid:id>/", update_restaurant, name="update_restaurant"
    ),
    path("api/restaurants/<uuid:id>/", restaurant_detail, name="restaurant_detail"),
    path("api/restaurants/<uuid:id>/create_food/", create_food, name="create_food"),
    path(
        "api/restaurants/<uuid:restaurant_id>/delete_food/<uuid:food_id>/",
        delete_food,
        name="delete_food",
    ),
    path(
        "api/restaurants/<uuid:restaurant_id>/update_food/<uuid:food_id>/",
        update_food,
        name="update_food",
    ),
]

roso_jogja/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("restaurant/", include("restaurant.urls")),
    path("wishlist/", include("wishlist.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("order/", include("cart_and_order.urls")),
    path("promo/", include("promo.urls")),
    path("reviews/", include("review.urls")),  # Menyertakan urls.py dari app review
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wishlist/urls.py
from django.urls import path
from . import views

app_name = 'wishlist'
urlpatterns = [
    path('', views.wishlist_view, name='wishlist_view'),  # URL untuk melihat wishlist
    path('add/<uuid:restaurant_id>/', views.add_to_wishlist, name='add_to_wishlist'),  # URL untuk menambah item ke wishlist
    path('remove/<uuid:restaurant_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),  # URL untuk menghapus item dari wishlist
    path('wishlist/status/', views.wishlist_status, name='wishlist_status'),
    path('wishlist/status/count/', views.wishlist_count, name='wishlist_count'),  # URL untuk menghitung jumlah wishlist
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% block meta %}
        {% endblock meta %}
        <script src="https://cdn.tailwindcss.com"></script>
        {% include 'tailwind-config.html' %}
        <link rel="stylesheet" href="{% static 'css/global.css' %}" />
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    </head>
    <body class="bg-orange-50">
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/navbar.html
{% load static %}
<nav class="fixed top-0 left-0 z-40 w-screen bg-white shadow-md font-['Poppins']">
    <div class="w-full mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
            <div class="flex items-center">
                <img src="{% static 'images/logo.png' %}"
                     alt="RosoJogja logo"
                     class="h-10 w-10 mr-2" />
                <a href="{% url 'main:show_main' %}">
                    <h1 class="text-xl font-bold text-[#FF7043] text-center">RosoJogja</h1>
                </a>
            </div>
            <div class="hidden md:flex items-center max-h-full">
                <a href="{% url 'main:show_main' %}"
                   class="text-[#333333] text-sm font-bold py-2 px-4 transition duration-300 text-center hover:text-[#FF7043]">Home</a>
                <a href="{% url 'restaurant:show_restaurants' %}"
                   class="text-[#333333] text-sm font-bold py-2 px-4 transition duration-300 text-center hover:text-[#FF7043]">Restaurants</a>
                {% if user.is_authenticated and user.role == 'C' %}
                    <a href="{% url 'order:show_cart' %}"
                       class="text-[#333333] text-sm font-bold py-2 px-4 transition duration-300 text-center hover:text-[#FF7043]">Cart</a>
                {% endif %}
                {% if user.is_authenticated %}
                    <a href="{% url 'promo:promo_home' %}"
                       class="text-[#333333] text-sm font-bold py-2 px-4 transition duration-300 text-center hover:text-[#FF7043]">Promo</a>
                    <!-- Wishlist dengan badge jumlah -->
                    <a href="{% url 'wishlist:wishlist_view' %}"
                       class="text-[#333333] text-sm font-bold py-2 px-4 transition duration-300 text-center hover:text-[#FF7043]">
                        <!-- Wishlist Logo -->
                        <span>Wishlist</span>
                        <span id="wishlist-count"
                              class="hidden bg-red-500 text-white text-xs font-bold rounded-full h-5 w-5 flex items-center justify-center absolute top-0 right-0 -mr-2 -mt-1">0</span>
                    </a>
                {% endif %}
            </div>
            <div class="hidden md:flex items-center max-h-full relative">
                {% if user.is_authenticated %}
                    <div class="flex items-center relative gap-2">
                        <div class="flex items-center">
                            <img src="{% if user.profile_picture %}{{ user.profile_picture.url }}{% else %}{% static 'images/default_profile_picture.png' %}{% endif %}"
                                 alt="User profile image"
                                 class="object-cover h-8 w-8 rounded-full mr-1" />
                            <button id="dropdown-trigger" class="focus:outline-none ml-1">
                                <svg class="w-4 h-4 text-[#333333] transition-transform"
                                     fill="none"
                                     stroke="currentColor"
                                     viewBox="0 0 24 24"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                                </svg>
                            </button>
                        </div>
                        <!-- Dropdown Menu -->
                        <div id="dropdown-menu"
                             class="hidden absolute top-12 right-0 mt-2 w-40 bg-white border border-gray-200 rounded-lg shadow-lg">
                            {% if user.role == 'C' %}
                                <a href="{% url 'order:show_order_history' %}"
                                   class="block px-4 py-2 text-sm text-[#333333] hover:bg-gray-100 hover:text-[#FF7043]">Order History</a>
                            {% endif %}
                            <a href="{% url 'main:logout' %}"
                               class="block px-4 py-2 text-sm text-[#333333] hover:bg-gray-100 hover:text-[#FF7043]">Logout</a>
                        </div>
                    </div>
                {% else %}
                    <a href="{% url 'main:login' %}"
                       class="bg-[#FF7043] text-white text-sm font-bold py-2 px-4 rounded transition duration-300 text-center mr-2 hover:bg-orange-600">Login</a>
                    <a href="{% url 'main:register' %}"
                       class="bg-[#D13529] text-white text-sm font-bold py-2 px-4 rounded transition duration-300 text-center hover:bg-red-800">Register</a>
                {% endif %}
            </div>
            <div class="md:hidden flex items-center">
                <button class="mobile-menu-button">
                    <svg class="w-6 h-6 text-[#D13529]"
                         fill="none"
                         stroke-linecap="round"
                         stroke-linejoin="round"
                         stroke-width="2"
                         viewBox="0 0 24 24"
                         stroke="currentColor">
                        <path d="M4 6h16M4 12h16M4 18h16"></path>
                    </svg>
                </button>
            </div>
        </div>
    </div>
    <!-- Mobile menu -->
    <div class="mobile-menu hidden md:hidden px-4 w-full md:max-w-full">
        <div class="pt-2 pb-3 space-y-1 mx-auto">
            {% if user.is_authenticated %}
                <div class="border-b-2 flex flex-row items-center justify-center py-2 border-[#D0A070]">
                    <div class="flex justify-center items-center px-2">
                        <img src="{% if user.profile_picture %}{{ user.profile_picture.url }}{% else %}{% static 'images/default_profile_picture.png' %}{% endif %}" alt="User profile image" class="object-cover h-8 w-8 rounded-full" />
                    </div>
                    <span class="text-[#333333] text-sm block px-3 py-2">Welcome, <b>{{ user.username }}</b></span>
                </div>

                <!-- Authenticated User Links -->
                <a href="{% url 'main:show_main' %}" class="block text-center font-bold py-2 px-4 transition duration-300 text-[#333333] hover:text-[#FF7043]" style="font-size: 0.875rem;">Home</a>
                <a href="{% url 'restaurant:show_restaurants' %}" class="block text-center font-bold py-2 px-4 transition duration-300 text-[#333333] hover:text-[#FF7043]" style="font-size: 0.875rem;">Restaurants</a>
                {% if user.role == 'C' %}
                    <a href="{% url 'order:show_cart' %}" class="block text-center font-bold py-2 px-4 transition duration-300 text-[#333333] hover:text-[#FF7043]" style="font-size: 0.875rem;">Cart</a>
                {% endif %}
                <a href="{% url 'promo:promo_home' %}" class="block text-center font-bold py-2 px-4 transition duration-300 text-[#333333] hover:text-[#FF7043]" style="font-size: 0.875rem;">Promo</a>
                {% if user.role == 'C' %}
                <a href="{% url 'wishlist:wishlist_view' %}" class="block text-center font-bold py-2 px-4 transition duration-300 text-[#333333] hover:text-[#FF7043]" style="font-size: 0.875rem;">Wishlist</a>
                    <a href="{% url 'order:show_order_history' %}" class="block text-center font-bold py-2 px-4 transition duration-300 text-[#333333] hover:text-[#FF7043]" style="font-size: 0.875rem;">Order History</a>
                {% endif %}
                <a href="{% url 'main:logout' %}" class="block text-center font-bold py-2 px-4 rounded transition duration-300" style="background-color: #D13529; color: #FFFFFF; font-size: 0.875rem;">Logout</a>
            {% else %}
                <!-- Guest User Links -->
                <a href="{% url 'main:show_main' %}" class="block text-center font-bold py-2 px-4 transition duration-300 text-[#333333] hover:text-[#FF7043]" style="font-size: 0.875rem;">Home</a>
                <a href="{% url 'restaurant:show_restaurants' %}" class="block text-center font-bold py-2 px-4 transition duration-300 text-[#333333] hover:text-[#FF7043]" style="font-size: 0.875rem;">Restaurants</a>
                <a href="{% url 'main:login' %}" class="block text-center font-bold py-2 px-4 rounded transition duration-300 mb-2" style="background-color: #FF7043; color: #FFFFFF; font-size: 0.875rem;">Login</a>
                <a href="{% url 'main:register' %}" class="block text-center font-bold py-2 px-4 rounded transition duration-300" style="background-color: #D13529; color: #FFFFFF; font-size: 0.875rem;">Register</a>

            {% endif %}
        </div>
    </div>
        <script>
        // Mobile menu functionality
        const btn = document.querySelector("button.mobile-menu-button");
        const menu = document.querySelector(".mobile-menu");

        btn.addEventListener("click", () => {
            menu.classList.toggle("hidden");
        });

        // Profile dropdown functionality
        const dropdownTrigger = document.getElementById('dropdown-trigger');
        const dropdownMenu = document.getElementById('dropdown-menu');
        let isDropdownOpen = false;

        if (dropdownTrigger && dropdownMenu) {
            // Toggle dropdown when clicking the chevron
            dropdownTrigger.addEventListener('click', (e) => {
                e.stopPropagation();
                isDropdownOpen = !isDropdownOpen;
                dropdownMenu.classList.toggle('hidden');
                dropdownTrigger.querySelector('svg').style.transform = isDropdownOpen ? 'rotate(180deg)' : 'rotate(0)';
            });

            // Close dropdown when clicking outside
            document.addEventListener('click', (e) => {
                if (!dropdownMenu.contains(e.target) && !dropdownTrigger.contains(e.target)) {
                    dropdownMenu.classList.add('hidden');
                    dropdownTrigger.querySelector('svg').style.transform = 'rotate(0)';
                    isDropdownOpen = false;
                }
            });
        }
        </script>
    </nav>

templates/tailwind-config.html
<script>
  tailwind.config = {
    theme: {
      extend: {
        colors: {
          "rj-orange": "#FF7044",
          "rj-gray": "#333333",
        },
      },
    },
  };
</script>